version: '3.8'
services:
  db:
    image: postgres:13
    container_name: medical_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user_mvp
      POSTGRES_PASSWORD: password_mvp
      POSTGRES_DB: medical_mvp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: